[package]
name = "read_and_write_files"
version = "0.1.0"
authors = ["Jaxel Rojas <jaxelr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"same-file" = "1.0.6"
"memmap" = "0.7.0"